symfonycasts_tailwind:
    # Specify the EXACT version of Tailwind CSS you want to use
    #binary_version: 'v4.1.11'
    binary : 'node_modules/.bin/tailwindcss'
    input_css: '%kernel.project_dir%/assets/styles/app.css'

    # Alternatively, you can specify the path to the binary that you manage yourself
    #binary: 'node_modules/.bin/tailwindcss'
