framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            crowdin:
                    dsn: '%env(resolve:CROWDIN_DSN)%'
                    domains: ['messages', 'validators', 'security', 'emails', 'app']
                    locales: ['fr', 'en']
